### ISSUE TITLE
Error while running image.py

### ISSUE THREAD

**Issue by dhaval-zala-aivid** [hnuzhy/SemiUHPE#1]
cmd: `python image.py DAD-COCOHead-ResNet50-best --is_full_range --config settings/DAD3DHeads_COCOHead.yml   --network resnet50 --gpu_ids 0`

**ERROR**: 
train_labeled       : DAD3DHeads
train_unlabeled     : COCOHead
type_unsuper        : ce
ulb_batch_ratio     : 4.0
val_frequency       : 1000
Traceback (most recent call last):
  File "image.py", line 125, in <module>
    config = get_config('test')
  File "/home/dhavalsinh/Desktop/research/face_direction/semiuhpe/src/config.py", line 195, in get_config
    config = Config(phase)
  File "/home/dhavalsinh/Desktop/research/face_direction/semiuhpe/src/config.py", line 37, in __init__
    self.exp_detail, self.date, self.ckpt = self.test_ckpt.split('/')
ValueError: not enough values to unpack (expected 3, got 1)

I think there is some problem within the code

the same issue occurs with video.py

**Comment by hnuzhy** [comment]
You need to download the released weight file `DAD-COCOHead-ResNet50-best` from my [huggingface link](https://huggingface.co/HoyerChou/SemiUHPE/blob/main/DAD-COCOHead-ResNet50-best.pth)

**Comment by dhaval-zala-aivid** [comment]
@hnuzhy Again getting the same error...!!


```
stage1_iteration    : 50000
std_ratio           : 3.0
test_ckpt           : DAD-COCOHead-ResNet50-best.pth
test_set            : DAD3DHeads
train_labeled       : DAD3DHeads
train_unlabeled     : COCOHead
type_unsuper        : ce
ulb_batch_ratio     : 4.0
val_frequency       : 1000
Traceback (most recent call last):
  File "image.py", line 125, in <module>
    config = get_config('test')
  File "/home/dhavalsinh/Desktop/research/face_direction/semiuhpe/src/config.py", line 195, in get_config
    config = Config(phase)
  File "/home/dhavalsinh/Desktop/research/face_direction/semiuhpe/src/config.py", line 37, in __init__
    self.exp_detail, self.date, self.ckpt = self.test_ckpt.split('/')
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by hnuzhy** [comment]
Maybe you need to change the `test_ckpt` into `SSL1.0_r0.05_ce_effinetv2_tDyna0.75_b64_ema_RO_CO_CM_full/Julxx_xxxxxx/best`, otherwise the `self.exp_detail` and `self.date` will not be parsed. Also remember to build the folder `exps/SSL1.0_r0.05_ce_effinetv2_tDyna0.75_b64_ema_RO_CO_CM_full/Julxx_xxxxxx/` in your root path.

**Comment by hnuzhy** [comment]
For example, you can manually build a hierarchical folder with path `exps/DAD3DHeads_COCOHead/SSL1.0_r0.05_ce_effinetv2_tDyna0.75_b32_ema_RO_CO_CM_full/Jul18_100557/` under the root path `./SemiUHPE`. Then, you can put the downloaded file  https://huggingface.co/HoyerChou/SemiUHPE/blob/main/DAD-WildHead-EffNetV2-S-best.pth into the new path. Finally, you may successfully run the inference script.
